name: flutter_yaax
description: An app about obio ecommerce

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  #own added dependecies
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  dio: ^4.0.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  cached_network_image: ^3.0.0
  intro_slider: ^3.0.2
  google_fonts: ^2.1.0
  salomon_bottom_bar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # Gotham Antonio
  fonts:
   - family: Gotham
     fonts:
      - asset: fonts/gotham/GothamBook.ttf
      - asset: fonts/gotham/GothamMedium.ttf
        weight: 500
      - asset: fonts/gotham/GothamBold.ttf
        weight: 700
